version: '3.8'

services:
  kitchen_service:
    build:
      context: modules/kitchen
      dockerfile: dockerfiles/Dockerfile
      target: production
    image: lsalazar/free_meal_kitchen
    depends_on:
      - kitchen_database
    environment:
      DB_HOST: "${KITCHEN_DB_HOST:-database}"
      DB_PORT: "${KITCHEN_DB_PORT:-3306}"
      DB_DATABASE: "${KITCHEN_DB_DATABASE:-kitchen}"
      DB_USERNAME: "${KITCHEN_DB_USERNAME:-kitchen}"
      DB_PASSWORD: "${KITCHEN_DB_PASSWORD-password}"
      WAREHOUSE_PROTOCOL: "${KITCHEN_WAREHOUSE_PROTOCOL:-http}"
      WAREHOUSE_DOMAIN: "${KITCHEN_WAREHOUSE_DOMAIN:-warehouse}"
    links:
      - "kitchen_database:database"
    networks:
      - kitchen
    restart: unless-stopped

  kitchen_web_server:
    image: library/nginx:1.21.4
    depends_on:
      - kitchen_service
    links:
      - "kitchen_service:app"
    networks:
      - kitchen
      - default
    restart: unless-stopped
    volumes:
      - ./modules/kitchen/public:/usr/share/nginx/html
      - ./modules/kitchen/dockerfiles/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  kitchen_database:
    image: library/mariadb:10.7.1
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: "${KITCHEN_DB_DATABASE:-kitchen}"
      MARIADB_USER: "${KITCHEN_DB_USERNAME:-kitchen}"
      MARIADB_PASSWORD: "${KITCHEN_DB_PASSWORD-password}"
    networks:
      - kitchen
    restart: unless-stopped
    volumes:
      - kitchen_database_data:/var/lib/mysql

  warehouse_service:
    build:
      context: modules/warehouse
      dockerfile: dockerfiles/Dockerfile
      target: production
    image: lsalazar/free_meal_warehouse
    depends_on:
      - warehouse_database
    environment:
      DB_HOST: "${WAREHOUSE_DB_HOST:-database}"
      DB_PORT: "${WAREHOUSE_DB_PORT:-3306}"
      DB_DATABASE: "${WAREHOUSE_DB_DATABASE:-warehouse}"
      DB_USERNAME: "${WAREHOUSE_DB_USERNAME:-warehouse}"
      DB_PASSWORD: "${WAREHOUSE_DB_PASSWORD-password}"
      KITCHEN_PROTOCOL: "${WAREHOUSE_KITCHEN_PROTOCOL:-http}"
      KITCHEN_DOMAIN: "${WAREHOUSE_KITCHEN_DOMAIN:-kitchen}"
      FOOD_SHOP_PROTOCOL: "${WAREHOUSE_FOOD_SHOP_PROTOCOL:-http}"
      FOOD_SHOP_DOMAIN: "${WAREHOUSE_FOOD_SHOP_DOMAIN:-food-shop}"
    links:
      - "warehouse_database:database"
    networks:
      - warehouse
    restart: unless-stopped

  warehouse_app_scheduler:
    build:
      context: modules/warehouse
      dockerfile: dockerfiles/Dockerfile
      target: app_scheduler
    image: lsalazar/free_meal_warehouse_app_scheduler
    depends_on:
      - warehouse_database
    environment:
      DB_HOST: "${WAREHOUSE_DB_HOST:-database}"
      DB_PORT: "${WAREHOUSE_DB_PORT:-3306}"
      DB_DATABASE: "${WAREHOUSE_DB_DATABASE:-warehouse}"
      DB_USERNAME: "${WAREHOUSE_DB_USERNAME:-warehouse}"
      DB_PASSWORD: "${WAREHOUSE_DB_PASSWORD-password}"
      KITCHEN_PROTOCOL: "${WAREHOUSE_KITCHEN_PROTOCOL:-http}"
      KITCHEN_DOMAIN: "${WAREHOUSE_KITCHEN_DOMAIN:-kitchen}"
      FOOD_SHOP_PROTOCOL: "${WAREHOUSE_FOOD_SHOP_PROTOCOL:-http}"
      FOOD_SHOP_DOMAIN: "${WAREHOUSE_FOOD_SHOP_DOMAIN:-food-shop}"
    links:
      - "warehouse_database:database"
    networks:
      - warehouse
    restart: unless-stopped

  warehouse_web_server:
    image: library/nginx:1.21.4
    depends_on:
      - warehouse_service
    links:
      - "warehouse_service:app"
    networks:
      - warehouse
      - default
    restart: unless-stopped
    volumes:
      - ./modules/warehouse/public:/usr/share/nginx/html
      - ./modules/warehouse/dockerfiles/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  warehouse_database:
    image: library/mariadb:10.7.1
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: "${WAREHOUSE_DB_DATABASE:-warehouse}"
      MARIADB_USER: "${WAREHOUSE_DB_USERNAME:-warehouse}"
      MARIADB_PASSWORD: "${WAREHOUSE_DB_PASSWORD-password}"
    networks:
      - warehouse
    restart: unless-stopped
    volumes:
      - warehouse_database_data:/var/lib/mysql

  web_server:
    image: library/nginx:1.21.4
    depends_on:
      - kitchen_web_server
      - warehouse_web_server
    links:
      - "kitchen_web_server:kitchen"
      - "warehouse_web_server:warehouse"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./dockerfiles/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/certs/domain.crt:/etc/ssl/certs/domain.crt
      - ./config/nginx/certs/domain.key:/etc/ssl/certs/domain.key


networks:
  kitchen:
  warehouse:

volumes:
  kitchen_database_data:
    driver: "local"
  warehouse_database_data:
    driver: "local"
